TranThienEm_12201094_BaiTapCoffeeShop/Models/Products.cs
namespace TranThienEm_12201094_BaiTapCoffeeShop.Models
{
    public class Products
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Detail { get; set; }
        public string? ImageUrl { get; set; }
        public decimal Price { get; set; }
        public bool IsTrendingProduct { get; set; }
    }
}

TranThienEm_12201094_BaiTapCoffeeShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace TranThienEm_12201094_BaiTapCoffeeShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TranThienEm_12201094_BaiTapCoffeeShop/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using TranThienEm_12201094_BaiTapCoffeeShop.Models.Interfaces;

namespace TranThienEm_12201094_BaiTapCoffeeShop.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository ProductRepository;
        public ProductsController(IProductRepository productRepository)
        {
            this.ProductRepository = productRepository;
        }
        public IActionResult Shop()
        {
            return View(ProductRepository.GetAllProducts());
        }
        public IActionResult Detail(int id)
        {
            var product = ProductRepository.GetProductDetail(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

TranThienEm_12201094_BaiTapCoffeeShop/Controllers/ShoppingCartController.cs
using TranThienEm_12201094_BaiTapCoffeeShop.Models.Interfaces;
using TranThienEm_12201094_BaiTapCoffeeShop.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace TranThienEm_12201094_BaiTapCoffeeShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IShoppingCartRepository shoppingCartRepository;
        private IProductRepository productRepository;
        public ShoppingCartController(IShoppingCartRepository
shoppingCartRepository, IProductRepository productRepository)
        {
            this.shoppingCartRepository = shoppingCartRepository;
            this.productRepository = productRepository;

        }

        public IActionResult Index()
        {
            var items = shoppingCartRepository.GetAllShoppingCartItems();
            shoppingCartRepository.ShoppingCartItems = items;
            ViewBag.TotalCart = shoppingCartRepository.GetShoppingCartTotal();
            return View(items);
        }

        public RedirectToActionResult AddToShoppingCart(int pId)
        {
            var product = productRepository.GetAllProducts().FirstOrDefault(p => p.Id == pId);
            if (product != null)
            {
                shoppingCartRepository.AddToCart(product);
                int cartCount = shoppingCartRepository.GetAllShoppingCartItems().Count();
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var product = productRepository.GetAllProducts().FirstOrDefault(p => p.Id == id);
            if (product != null)
            {
                shoppingCartRepository.RemoveFromCart(product);
                int cartCount = shoppingCartRepository.GetAllShoppingCartItems().Count();
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");
        }
    }
}

TranThienEm_12201094_BaiTapCoffeeShop/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@{
    var cartCount = HttpContextAccessor?.HttpContext?.Session.GetInt32("CartCount") ?? 0;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.7.8, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="~/assets/images/coffee-icon-sign-symbol-design-free-png.webp" type="image/x-icon">
    <meta name="description" content="">


    <title>Home</title>
    <link rel="stylesheet" href="~/assets/web/assets/mobirise-icons2/mobirise2.css">
    <link rel="stylesheet" href="~/assets/web/assets/mobirise-icons-bold/mobirise-icons-bold.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="~/assets/parallax/jarallax.css">
    <link rel="stylesheet" href="~/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="~/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="~/assets/theme/css/style.css">
    <link rel="preload"
          href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"
          as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap">
    </noscript>
    <link rel="preload" as="style" href="~/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="~/assets/mobirise/css/mbr-additional.css" type="text/css">
</head>

<body>
    <section data-bs-version="5.1" class="menu menu3 cid-tsEQosCCDP" once="menu" id="menu3-0">
        <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
            <div class="container">
                <div class="navbar-brand">
                    <span class="navbar-logo">
                        <a asp-controller="Home" asp-action="Index">
                            <img src="~/assets/images/coffee-icon-sign-symbol-design-free-png.webp" alt="Coffee Shop"
                                 style="height: 3rem;">
                        </a>
                    </span>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse"
                        data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <div class="hamburger">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                        <li class="nav-item">
                            <a class="nav-link link text-black show display-4" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link text-black show display-4" asp-controller="Products" asp-action="Shop">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link text-black show display-4"
                               asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <partial name="_LoginPartial"></partial>
                        <li class="nav-item">
                            <a class="nav-link link text-black show display-4" href="@Url.Action("Index", "ShoppingCart")">
                                <span class="mobi-mbri mobi-mbri-shopping-bag mbr-iconfont mbr-iconfont-btn"><small>(@cartCount)</small></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </section>


    @RenderBody()

    <section data-bs-version="5.1" class="footer7 cid-tsQdrs3Vrj" once="footers" id="footer7-13">
        <div class="container">
            <div class="media-container-row align-center mbr-white">
                <div class="col-12">
                    <p class="mbr-text mb-0 mbr-fonts-style display-7">
                        © Copyright 2025&nbsp; - All Rights Reserved
                    </p>
                </div>
            </div>
        </div>
    </section>

    <script src="~/assets/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/parallax/jarallax.js"></script>
    <script src="~/assets/smoothscroll/smooth-scroll.js"></script>
    <script src="~/assets/ytplayer/index.js"></script>
    <script src="~/assets/dropdown/js/navbar-dropdown.js"></script>
    <script src="~/assets/theme/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TranThienEm_12201094_BaiTapCoffeeShop/Views/Shared/_Product.cshtml
<div class="row mt-4">
    @foreach (var item in Model)
    {
        <div class="item features-image сol-12 col-md-6 col-lg-4">
            <div class="item-wrapper">
                <div class="item-img">
                    <img src="@item.ImageUrl" alt="Coffee Shop" title="">
                </div>
                <div class="item-content">
                    <a asp-controller="Products" asp-action="Detail" asp-route-id="@item.Id"
                       target="_self">
                        <h6 class="item-subtitle mbr-fonts-style mt-1 display 7">
                            <strong>@item.Name</strong>
                        </h6>
                    </a>
                    <p class="mbr-text mbr-fonts-style mt-3 display 7">@item.Price.ToString("C")</p>
                </div>
                <div class="mbr-section-btn item-footer mt-2">
                    <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-pId="@item.Id" class="btn item-btn btn-primary display-4" target="_self">
                        <span class="mbrib-cart-add mbr-iconfont mbr-iconfont-btn"></span>Add
                        to cart&nbsp;
                    </a>
                </div>
            </div>
        </div>
    }
</div>